name: explo
repository: https://github.com/blaugold/explo
packages:
  - 'packages/**'

command:
  version:
    linkToCommits: true

scripts:
  formatting:check:
    run: dart format -o none --set-exit-if-changed .
  formatting:write:
    run: dart format .
  analyze:
    run: melos exec -c 1 -- flutter analyze
  test:flutter:unit:
    run: melos exec -c 1 -- flutter test -r expanded
    select-package:
      flutter: true
      dir-exists: test
  test:flutter:integration:
    run: melos exec -c 1 -- flutter test -r expanded integration_test
    select-package:
      flutter: true
      dir-exists: integration_test
  explo_ide_view:build:
    run: ./tools/explo_ide_view.sh build
  explo_ide_view:copy:vs_code:
    run: ./tools/explo_ide_view.sh copyToExploCode
  explo_ide_view:vs_code:
    'melos run explo_ide_view:build && melos run explo_ide_view:copy:vs_code'
