name: explo_capture_example
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  explo_capture:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  integration_test:
    sdk: flutter
  vm_service: ^7.3.0

flutter:
  uses-material-design: true
