name: explo_ide_view
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  explo:
    path: ../explo
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
